development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://:notification123@pub-redis-17414.us-east-1-2.4.ec2.garantiadata.com:17414
  port: 17414
  password: notification123
  inline: true
